### ISSUE TITLE
Check your firewall allows inbound traffic on ports 8080,9090 on XBMC machine

### ISSUE THREAD

**Issue by suryatejabolikonda** [ncarthy/kodi-crestron#15]
Hi All,
I got something different error from xbmc. When i connect to windows 7 KODI15, it is saying that
" Check your firewall allows inbound traffic on ports 8080,9090 on XBMC machine."
But i checked firewall for windows7, it is disabled. I also checked all the xbmc settings all settings are enabled correctly. and those ports(8080 and 9090) are open for that machine(windows7).

When i restart my Crestron Processor it will work for some time and again it will show same error.

Kindly suggest me for this Thread.

**Comment by ncarthy** [comment]
You also need to make sure port 9777 is open.
