### ISSUE TITLE
Will no longer connect to XBMC

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ncarthy/kodi-crestron#2]
```
The only change I can think of that I made recently was installing the Crestron 
Studio software.  At some point after doing that, I wanted to make a change to 
my system.  After compiling and uploading I noticed I could no longer control 
my XBMC.  So I loaded the pre-compiled version from the download (xbmc-test) 
and it connected fine.

I was using version .6 but updated to the latest 1.01beta to see if that would 
fix it.

The error I'm getting in debugger anytime I try to send a command is "Not 
connected to XBMC at 192.168.1.201. Socket Error number is -1."

The processor is a Prodigy PMC3, my machine is Win7 x64, and I have the latest 
version of all Crestron software.

Have you seen this error before?
```

Original issue reported on code.google.com by `matthews...@gmail.com` on 29 Dec 2012 at 2:04

**Comment by suryatejabolikonda** [comment]
Hi All,
   I got something different error from xbmc. When i connect to windows 7 KODI15, it is saying that
" Check your firewall allows inbound traffic on ports 8080,9090 on XBMC machine."
But i checked firewall for windows7, it is disabled. I also checked all the xbmc settings all settings are enabled correctly. and those ports(8080 and 9090) are open for that machine(windows7).

When i restart my Crestron Processor it will work for some time and again it will show same error.

Kindly suggest me for this Thread.
